name: Ahmed Shaikh
favicon: null
layout_spectrum: 0.39406471513211727
typography_spectrum: 0.8637267269659787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9340363170485944
  lightness: 0.8853107476606965
  saturation: 0.34152822801843286
  rhythmicContrast: 0.8823150475509465
purpose: []
